### ISSUE TITLE
linking to individual cities

### ISSUE THREAD

**Issue by mapmeld** [mapzen/metroextractor-cities#236]
this is a minor issue

can you add an \<a name="#{city_name}"\>\</a\> to each of the city listings, so that it's possible to link to points on the page? Or link to the letter filter using #u for cities starting with U?

**Comment by KathleenLD** [comment]
@mapmeld we were discussing this internally. There are some architectural reasons that this is tricksy, but it's on our medium-term roadmap. @louh any other thoughts/feels to add?

**Comment by louh** [comment]
Sure - basically, this is super easy if we were building the page server side, but we're not - we're asking the client to download the list of cities and build the page on the client side. So a browser given #link would have no place to go when the page loads. We could _probably_ just write a script that runs after the page is constructed, checks the page hash and then tries to reload it (hopefully, the browser knows to scroll the page to the identifier instead of refreshing?). But I think internally we would rather just do the right thing and start building / caching the page server side, because that would improve the loading speed and user experience generally, and we can link to identifiers within the page without having to add more tricks.

**Comment by abinashn1** [comment]
Please add this city
Nepal Pokhara
W:83.886108
N:28.29894
S:28.178862
E:84.05571

**Comment by migurski** [comment]
Why not build the page server-side? There are enough cities that the DOM build time is creaky and loagy.

**Comment by louh** [comment]
That's a great idea, @migurski !!!! I think if you told someone to do it, it will happen!

**Comment by migurski** [comment]
I’m actually asking. :|

**Comment by louh** [comment]
I don't think there's any reason why we couldn't - we just have to bump it up in priority

**Comment by migurski** [comment]
Cool thanks. Is this the repo that does that actual work? https://github.com/mapzen/chef-metroextractor

**Comment by louh** [comment]
That's the one that does the extraction work. The download page is hosted on the Rails portion of mapzen.com - not a public repository so I can't/won't link to it but I will link to this one: https://github.com/NelsonMinar/metro-extracts/tree/gh-pages. It is still fundamentally the same thing but the html is a Rails view.

We have a pretty good workflow of mounting static pages to mapzen.com now, so the way I envision it is that whenever the extractor extracts the extractions there might also be a task to generate a static page with all the stuff already on it.

**Comment by migurski** [comment]
Yeah that would make sense to me as well. I’ll root around in the Rails stuff, see if I can make some sense of it.

**Comment by louh** [comment]
@mapmeld @KathleenLD Remember this?
It's live :) for example: https://mapzen.com/data/metro-extracts/#asheville-north-carolina
