### ISSUE TITLE
"but downloads for other cities range from 2 MB to 350 MB"

### ISSUE THREAD

**Issue by laurensskelly** [mapzen/metroextractor-cities#418]
So which is the smallest .osm city?
Wanted Melbourne, Aus but it's 54M, tried Honolulu but 3.5M .gz becomes 47M .osm 
(I have a 25MB limit).
Or can I get subsets?
Tah

**Comment by rmglennon** [comment]
If you want to do the tutorial, which has that statement in the requirements section (https://mapzen.com/documentation/metro-extracts/walkthrough/#requirements), you will actually be downloading geojson or shapefile format, not the actual .osm file. Those are about 50 mb download and don't get all that much bigger unzipped. There is not a way to get subsets of data beyond the files listed on the page.

Otherwise, I'm not sure which is the smallest file. It would be for a less populous city with a small border.

**Comment by laurensskelly** [comment]
Thanks, found one of reasonable size by trawling, yellowknife_canada.osm
