### ISSUE TITLE
Lisbon, Portugal

### ISSUE THREAD

**Issue by galo255** [mapzen/metroextractor-cities#471]
Lisbon, Portugal

**Comment by rmglennon** [comment]
It looks like Lisbon is in the list of extracts. https://mapzen.com/data/metro-extracts/#lisbon-portugal

It is the example shown in this tutorial about Metro Extracts: https://mapzen.com/documentation/metro-extracts/walkthrough/

I am going to close this issue, but please comment if you were posting this because there was a problem with Lisbon. Thanks!
